// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tPeYq672jS4rBP_HHPKOwJJncoql5Lg',
    appId: '1:922136513534:web:96136d548a30fa8c76ceaf',
    messagingSenderId: '922136513534',
    projectId: 'actividad7-24664',
    authDomain: 'actividad7-24664.firebaseapp.com',
    storageBucket: 'actividad7-24664.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0hIEvy5yJaMZhi4zmUNo5Y4g0PtzKS4',
    appId: '1:922136513534:android:5ba579e977a72f0c76ceaf',
    messagingSenderId: '922136513534',
    projectId: 'actividad7-24664',
    storageBucket: 'actividad7-24664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfb-qlNgI8e6jERrOQQinya-RdWWAws4I',
    appId: '1:922136513534:ios:be50c59796f3c97b76ceaf',
    messagingSenderId: '922136513534',
    projectId: 'actividad7-24664',
    storageBucket: 'actividad7-24664.firebasestorage.app',
    iosBundleId: 'com.example.otaijuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfb-qlNgI8e6jERrOQQinya-RdWWAws4I',
    appId: '1:922136513534:ios:be50c59796f3c97b76ceaf',
    messagingSenderId: '922136513534',
    projectId: 'actividad7-24664',
    storageBucket: 'actividad7-24664.firebasestorage.app',
    iosBundleId: 'com.example.otaijuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9tPeYq672jS4rBP_HHPKOwJJncoql5Lg',
    appId: '1:922136513534:web:5516d70a4cfb76bc76ceaf',
    messagingSenderId: '922136513534',
    projectId: 'actividad7-24664',
    authDomain: 'actividad7-24664.firebaseapp.com',
    storageBucket: 'actividad7-24664.firebasestorage.app',
  );
}
